//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaloniaRisovaviti.Assets {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvaloniaRisovaviti.Assets.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About App.
        /// </summary>
        public static string aboutApp {
            get {
                return ResourceManager.GetString("aboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add New Canvas.
        /// </summary>
        public static string addNewCanvas {
            get {
                return ResourceManager.GetString("addNewCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Add Version.
        /// </summary>
        public static string addVersion {
            get {
                return ResourceManager.GetString("addVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Work.
        /// </summary>
        public static string addWork {
            get {
                return ResourceManager.GetString("addWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на After generating a key, the previous key will be deleted.
        /// </summary>
        public static string afterGenerating {
            get {
                return ResourceManager.GetString("afterGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на App Settings.
        /// </summary>
        public static string appSettings {
            get {
                return ResourceManager.GetString("appSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect login or password.
        /// </summary>
        public static string authError {
            get {
                return ResourceManager.GetString("authError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Auth Error.
        /// </summary>
        public static string authErrortxt {
            get {
                return ResourceManager.GetString("authErrortxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passwords &amp; Auth Settings.
        /// </summary>
        public static string authSettings {
            get {
                return ResourceManager.GetString("authSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Canvas.
        /// </summary>
        public static string canvas {
            get {
                return ResourceManager.GetString("canvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Canvases.
        /// </summary>
        public static string canvases {
            get {
                return ResourceManager.GetString("canvases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change Password.
        /// </summary>
        public static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connected Devices.
        /// </summary>
        public static string connectedDevices {
            get {
                return ResourceManager.GetString("connectedDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection Error.
        /// </summary>
        public static string connectionError {
            get {
                return ResourceManager.GetString("connectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create New Project.
        /// </summary>
        public static string createNewProject {
            get {
                return ResourceManager.GetString("createNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete All.
        /// </summary>
        public static string deleteAll {
            get {
                return ResourceManager.GetString("deleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drafts.
        /// </summary>
        public static string drafts {
            get {
                return ResourceManager.GetString("drafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email user.
        /// </summary>
        public static string EmailUser {
            get {
                return ResourceManager.GetString("EmailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Enter Code.
        /// </summary>
        public static string enterCode {
            get {
                return ResourceManager.GetString("enterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login or password was entered incorrectly.
        /// </summary>
        public static string enteredIncorrectly {
            get {
                return ResourceManager.GetString("enteredIncorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Login.
        /// </summary>
        public static string enterLogin {
            get {
                return ResourceManager.GetString("enterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entrance.
        /// </summary>
        public static string Entrance {
            get {
                return ResourceManager.GetString("Entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Fill in the Field.
        /// </summary>
        public static string fillField {
            get {
                return ResourceManager.GetString("fillField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Fill Out Form.
        /// </summary>
        public static string fillForm {
            get {
                return ResourceManager.GetString("fillForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forgot your password?.
        /// </summary>
        public static string forgetPasswort {
            get {
                return ResourceManager.GetString("forgetPasswort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generating a key.
        /// </summary>
        public static string generatingkey {
            get {
                return ResourceManager.GetString("generatingkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to Auth Tab.
        /// </summary>
        public static string goToAuthTab {
            get {
                return ResourceManager.GetString("goToAuthTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Inherit from version.
        /// </summary>
        public static string inheritVersion {
            get {
                return ResourceManager.GetString("inheritVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insert Image.
        /// </summary>
        public static string insertImage {
            get {
                return ResourceManager.GetString("insertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key.
        /// </summary>
        public static string key {
            get {
                return ResourceManager.GetString("key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You agree to [privacy terms](http://localhost:32806/privacy.html).
        /// </summary>
        public static string MDAgreement {
            get {
                return ResourceManager.GetString("MDAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  More.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Canvases.
        /// </summary>
        public static string myCanvases {
            get {
                return ResourceManager.GetString("myCanvases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Drafts.
        /// </summary>
        public static string myDrafts {
            get {
                return ResourceManager.GetString("myDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Versions.
        /// </summary>
        public static string myVersions {
            get {
                return ResourceManager.GetString("myVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Risovavity Avalonia.
        /// </summary>
        public static string NameApp {
            get {
                return ResourceManager.GetString("NameApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string NameOfUser {
            get {
                return ResourceManager.GetString("NameOfUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Password.
        /// </summary>
        public static string newPassword {
            get {
                return ResourceManager.GetString("newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Version.
        /// </summary>
        public static string newVersion {
            get {
                return ResourceManager.GetString("newVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Old Password.
        /// </summary>
        public static string oldPassword {
            get {
                return ResourceManager.GetString("oldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Old Version.
        /// </summary>
        public static string oldVersion {
            get {
                return ResourceManager.GetString("oldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parent.
        /// </summary>
        public static string parent {
            get {
                return ResourceManager.GetString("parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile Settings.
        /// </summary>
        public static string profileSettings {
            get {
                return ResourceManager.GetString("profileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project.
        /// </summary>
        public static string project {
            get {
                return ResourceManager.GetString("project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recovery Methods.
        /// </summary>
        public static string recoveryMethods {
            get {
                return ResourceManager.GetString("recoveryMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account Recovery.
        /// </summary>
        public static string recoveryTitle {
            get {
                return ResourceManager.GetString("recoveryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registrating.
        /// </summary>
        public static string Registrating {
            get {
                return ResourceManager.GetString("Registrating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repeat New Password.
        /// </summary>
        public static string repeatNewPassword {
            get {
                return ResourceManager.GetString("repeatNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repeat password.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resource Search Error.
        /// </summary>
        public static string resourceSearchError {
            get {
                return ResourceManager.GetString("resourceSearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Role.
        /// </summary>
        public static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Changes.
        /// </summary>
        public static string saveChanges {
            get {
                return ResourceManager.GetString("saveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Security.
        /// </summary>
        public static string security {
            get {
                return ResourceManager.GetString("security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Existing Project.
        /// </summary>
        public static string selectExistingProject {
            get {
                return ResourceManager.GetString("selectExistingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set as main version.
        /// </summary>
        public static string setMainVersion {
            get {
                return ResourceManager.GetString("setMainVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You agree to the terms of confidentiality.
        /// </summary>
        public static string TextConfid {
            get {
                return ResourceManager.GetString("TextConfid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Two-Factor Authentication.
        /// </summary>
        public static string twoFactorAuth {
            get {
                return ResourceManager.GetString("twoFactorAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authors.
        /// </summary>
        public static string txtAuthors {
            get {
                return ResourceManager.GetString("txtAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authors works.
        /// </summary>
        public static string txtAuthorsWorks {
            get {
                return ResourceManager.GetString("txtAuthorsWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string txtLang {
            get {
                return ResourceManager.GetString("txtLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Liked .
        /// </summary>
        public static string txtLikedWork {
            get {
                return ResourceManager.GetString("txtLikedWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My work.
        /// </summary>
        public static string txtMyWork {
            get {
                return ResourceManager.GetString("txtMyWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings app.
        /// </summary>
        public static string txtSettingsApp {
            get {
                return ResourceManager.GetString("txtSettingsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Themes.
        /// </summary>
        public static string txtThemes {
            get {
                return ResourceManager.GetString("txtThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update.
        /// </summary>
        public static string txtUpdateInMainPage {
            get {
                return ResourceManager.GetString("txtUpdateInMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown Error.
        /// </summary>
        public static string unknownError {
            get {
                return ResourceManager.GetString("unknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upload Your Project.
        /// </summary>
        public static string uploadProject {
            get {
                return ResourceManager.GetString("uploadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Versions.
        /// </summary>
        public static string versions {
            get {
                return ResourceManager.GetString("versions", resourceCulture);
            }
        }
    }
}
